import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Les jardins de Ben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section id="ben">
          <div className={styles.presentation}>
            <div className={styles.profile}>
              <Image
                src="/images/ben.svg"
                alt="image 1"
                className={styles.images}
                width={300}
                height={300}
              />
            </div>
            <div className={styles.description}>
              <h2 className={styles.h2}>Qui est Ben ? </h2>
              <p className={styles.descriptionText}>
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero
                unde sequi hic corrupti obcaecati voluptates adipisci cupiditate
                placeat reiciendis, eos a ducimus veniam numquam quaerat
                laudantium doloremque accusamus quia harum. Accusamus earum
                autem, molestiae dolorum, vel impedit alias placeat ab animi
                laboriosam debitis deleniti nisi. Velit, incidunt debitis vitae
                illum quis consequuntur, eius alias corrupti beatae omnis, eum
                nulla similique. Dolorum, commodi ad voluptatibus excepturi
                laudantium"
              </p>
            </div>
          </div>
        </section>
        <section id="mesrealisations">
          <div className={styles.grid}>
            <h2 className={styles.h2}>Mes réalisations</h2>
            <ul className={styles.ul}>
              <li>
                <article className={styles.card}>
                  <Image
                    src="/images/1.jpg"
                    alt="image 1"
                    className={styles.images}
                    width={1920}
                    height={1280}
                  />
                  <p>
                    Description: Lorem, ipsum dolor sit amet consectetur
                    adipisicing elit. Reiciendis nemo culpa sequi
                  </p>
                </article>
              </li>
              <li>
                <article className={styles.card}>
                  <Image
                    src="/images/2.jpg"
                    alt="image 2"
                    className={styles.images}
                    width={1920}
                    height={1280}
                  />
                  <p>
                    Description: Lorem, ipsum dolor sit amet consectetur
                    adipisicing elit. Reiciendis nemo culpa sequi
                  </p>
                </article>
              </li>
              <li>
                <article className={styles.card}>
                  <Image
                    src="/images/3.jpg"
                    alt="image 3"
                    className={styles.images}
                    width={1920}
                    height={1280}
                  />
                  <p>
                    Description: Lorem, ipsum dolor sit amet consectetur
                    adipisicing elit. Reiciendis nemo culpa sequi
                  </p>
                </article>
              </li>
              <li>
                <article className={styles.card}>
                  <Image
                    src="/images/4.jpg"
                    alt="image 4"
                    className={styles.images}
                    width={1920}
                    height={1280}
                  />
                  <p>
                    Description: Lorem, ipsum dolor sit amet consectetur
                    adipisicing elit. Reiciendis nemo culpa sequi
                  </p>
                </article>
              </li>
              <li>
                <article className={styles.card}>
                  <Image
                    src="/images/5.jpg"
                    alt="image 5"
                    className={styles.images}
                    width={1920}
                    height={1280}
                  />
                  <p>
                    Description: Lorem, ipsum dolor sit amet consectetur
                    adipisicing elit. Reiciendis nemo culpa sequi
                  </p>
                </article>
              </li>
              <li>
                <article className={styles.card}>
                  <Image
                    src="/images/6.jpg"
                    alt="image 6"
                    className={styles.images}
                    width={1920}
                    height={1280}
                  />
                  <p>
                    Description: Lorem, ipsum dolor sit amet consectetur
                    adipisicing elit. Reiciendis nemo culpa sequi
                  </p>
                </article>
              </li>
            </ul>
          </div>
        </section>
        <section id="mespartenaires">Mes partenaires</section>
        <section>Contact</section>
      </main>
      <Footer />
    </div>
  );
}

const Header = () => {
  return (
    <div className={styles.header}>
      <div className={styles.headerBody}>
        <Image
          src="/images/2.jpg"
          alt="image 2"
          className={styles.headerLogo}
          width={120}
          height={40}
        />
        <ul className={styles.headerList}>
          <li></li>
          <li>
            <a href="#ben">Ben</a>
          </li>
          <li>
            <a href="#mesrealisations">Mes réalisations</a>
          </li>
          <li>
            <a href="#mespartenaires">Mes partenaires</a>
          </li>
        </ul>
        <div>|||</div>
      </div>
    </div>
  );
};

const Footer = () => {
  return (
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        <Link href="/">
          <a>
            <span className={styles.link}>Les jardins de Ben</span>
          </a>
        </Link>
      </a>
    </footer>
  );
};
